[platformio]
default_envs = tester
src_dir = .

[env:tester]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git#aa70b802be8851668053d4f09734e4089fe41932
framework = arduino
board = waveshare_rp2040_zero
board_build.core = earlephilhower
monitor_speed = 115200
lib_ldf_mode = deep+
platform_packages =
    framework-arduinopico@https://github.com/earlephilhower/arduino-pico.git#f08743846e999208b0695f419a3e5dd26c6e8058
lib_deps =
    bblanchon/ArduinoJson@7.4.3
    adafruit/Adafruit NeoPixel@1.15.2
