[platformio]
default_envs = normal
src_dir = .
data_dir = data
lib_dir = ../../libraries

[env]
platform = platformio/espressif8266@4.2.1
framework = arduino
board = esp12e
board_build.ldscript = eagle.flash.4m1m.ld
board_build.filesystem = littlefs
board_build.flash_mode = dout
board_build.f_cpu = 80000000L
board_build.f_flash = 40000000L
upload_speed = 512000
monitor_speed = 115200
lib_ldf_mode = deep+
extra_scripts =
    scripts/platformio_build.py
build_flags =
    -g
lib_deps =
    bblanchon/ArduinoJson@7.4.3
    tzapu/WiFiManager@2.0.17
    links2004/WebSockets@2.7.2
    adafruit/Adafruit NeoPixel@1.15.2

[env:normal]

[env:legacy]
build_flags =
    ${env.build_flags}
    -DUSE_LEGACY_HARDWARE=1

[env:gpio_fix]
build_flags =
    ${env.build_flags}
    -DUSE_GPIO_FIX_HARDWARE=1
    -DLED_WS2812_COLOR_ORDER=NEO_RGB

[env:test]
build_flags =
    ${env.build_flags}
    -DENABLE_TEST_HARNESS_API=1

[env:legacy_test]
build_flags =
    ${env.build_flags}
    -DUSE_LEGACY_HARDWARE=1
    -DENABLE_TEST_HARNESS_API=1
