#ifndef PROTOCOLSETTINGS_H
#define PROTOCOLSETTINGS_H

// UDP port
#define ARTNET_PORT 6454
#define ARTNET_PROTOCOL_VERSION 14

// Buffers
#define ARTNET_MAX_BUFFER 530
#define DMX_MAX_BUFFER 512

// Packet constants
#define ARTNET_ID "Art-Net"
#define ARTNET_DMX_START_LOC 18
#define ARTNET_SYNC_MIN_LENGTH 14
#define ARTNET_POLL_MIN_LENGTH 14
#define ARTNET_POLL_REPLY_MIN_LENGTH 207
#define ARTNET_ADDRESS_MIN_LENGTH 107
#define ARTNET_IP_PROG_MIN_LENGTH 26
#define ARTNET_IP_PROG_REPLY_LENGTH 34

#define ARTNET_AC_LED_NORMAL 0x02
#define ARTNET_AC_LED_MUTE 0x03
#define ARTNET_AC_LED_LOCATE 0x04
#define ARTNET_AC_CANCEL_MERGE 0x01
#define ARTNET_AC_FAIL_HOLD 0x08
#define ARTNET_AC_FAIL_ZERO 0x09
#define ARTNET_AC_FAIL_FULL 0x0A
#define ARTNET_AC_FAIL_SCENE 0x0B
#define ARTNET_AC_FAIL_RECORD 0x0C
#define ARTNET_AC_MERGE_LTP_0 0x10
#define ARTNET_AC_DIRECTION_TX_0 0x20
#define ARTNET_AC_DIRECTION_RX_0 0x30
#define ARTNET_AC_MERGE_HTP_0 0x50

#define ARTNET_IP_PROG_COMMAND_ENABLE 0x80
#define ARTNET_IP_PROG_COMMAND_DHCP 0x40
#define ARTNET_IP_PROG_COMMAND_DEFAULTS 0x08
#define ARTNET_IP_PROG_COMMAND_IP 0x04
#define ARTNET_IP_PROG_COMMAND_SUBNET 0x02
#define ARTNET_IP_PROG_COMMAND_PORT 0x01
#define ARTNET_IP_PROG_COMMAND_GATEWAY 0x10

static_assert(
  ARTNET_MAX_BUFFER >= ARTNET_DMX_START_LOC + DMX_MAX_BUFFER,
  "Art-Net buffer is too small for a full ArtDmx packet");

// Packet confines
#define ARTNET_SHORT_NAME_MAX_LENGTH 17
#define ARTNET_LONG_NAME_MAX_LENGTH 63

// DMX settings
#define DMX_MAX_OUTPUTS 4
#define DMX_MS_BETWEEN_TICKS 25

// RDM
#define DMX_RDM_STARTCODE 0xCC

#endif
